Traceback (most recent call last):
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------


df_num_corr = df_num[['normalized_salary', 'duration', 'applies', 'views']]

plt.figure(figsize=(15,5))
sns.heatmap(df_num_corr.select_dtypes(include=['number']).corr(), annot=True, cmap='coolwarm')
plt.yticks(rotation=0)
plt.title('Matriz de CorrelaciÃ³n: salario, duraciÃ³n, aplicaciones y vistas de las ofertas de trabajo')
plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m df_num_corr [38;5;241m=[39m [43mdf_num[49m[[[38;5;124m'[39m[38;5;124mnormalized_salary[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mduration[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mapplies[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mviews[39m[38;5;124m'[39m]]
[0;32m      3[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m15[39m,[38;5;241m5[39m))
[0;32m      4[0m sns[38;5;241m.[39mheatmap(df_num_corr[38;5;241m.[39mselect_dtypes(include[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mnumber[39m[38;5;124m'[39m])[38;5;241m.[39mcorr(), annot[38;5;241m=[39m[38;5;28;01mTrue[39;00m, cmap[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcoolwarm[39m[38;5;124m'[39m)

[1;31mNameError[0m: name 'df_num' is not defined

