Traceback (most recent call last):
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\Users\Sarah\Code\ProyectoABD\.venv\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load your csv') file
df = pd.read_csv(salary_cent,header=0,skiprows=1)

# Display the dataframe as a table
df
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[4], line 2[0m
[0;32m      1[0m [38;5;66;03m# Load your csv') file[39;00m
[1;32m----> 2[0m df [38;5;241m=[39m pd[38;5;241m.[39mread_csv([43msalary_cent[49m,header[38;5;241m=[39m[38;5;241m0[39m,skiprows[38;5;241m=[39m[38;5;241m1[39m)
[0;32m      4[0m [38;5;66;03m# Display the dataframe as a table[39;00m
[0;32m      5[0m df

[1;31mNameError[0m: name 'salary_cent' is not defined

